### PR TITLE
fix: support multiple "Set-Cookie" response headers

### LINKED ISSUE #44: Cannot set multiple cookies
Hello!

I've been trying many different ways to set multiple cookies on my responses with no luck.

Some of the tested approaches work on the browser (using`msw` directly), but none work while using the `http-middleware`.

For example, the following works perfectly using `msw` on the browser, but not using the `http-middleware`:

```js
    return HttpResponse.json(
        body,
        {
            headers: [
                [
                    'Set-Cookie',
                    `${COOKIE_NAMES.ACCESS_TOKEN}=${session.accessToken.value}; Path=/; Max-Age=${TOKENS.ACCESS_TOKEN_MAX_AGE};`
                ],
                [
                    'Set-Cookie',
                    `${COOKIE_NAMES.REFRESH_TOKEN}=${session.refreshToken.value}; Path=/; Max-Age=${TOKENS.REFRESH_TOKEN_EXP_MAX_AGE};`
                ]
            ]
        }
    );
```

Using the `http-middleware`, only the last cookie is sent from express.

Other approaches I tried involved using:
- `Headers` constructor (using `append`).
- `headers-polyfill`.
- Different overloads of `HttpResponse.json`.
- Native `Response.json`.

I have the following configuration before the `htttp-middleware`:

```js
app.use((req, res, next) => {
    res.header('Access-Control-Allow-Origin', req.get('origin') || '*');

    res.header('Access-Control-Allow-Credentials', 'true');

    res.header('Access-Control-Allow-Methods', '*');

    res.header(
        'Access-Control-Allow-Headers',
        'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers'
    );

    if (req.method === 'OPTIONS') {
        return res.sendStatus(200);
    }

    return next();
});

app.use(express.json());
```

Potentially related issues:
- https://github.com/mswjs/msw/issues/640
- https://github.com/mswjs/headers-polyfill/issues/29

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #44

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -60,7 +60,11 @@ export function createMiddleware(
           res.statusMessage = statusText
 
           headers.forEach((value, name) => {
-            res.setHeader(name, value)
+            /**
+             * @note Use `.appendHeader()` to support multi-value
+             * response headers, like "Set-Cookie".
+             */
+            res.appendHeader(name, value)
```
Comment (kettanaito) [inline src/middleware.ts:67]: Previously, `res.setHeader()` would only set the last value of a multi-value cookie, like `Set-Cookie`.

Using `res.appendHeader()` will support both single- and multi-value response cookies.

**Comment by kettanaito** [comment]
## Released: v0.10.1 🎉

This has been released in v0.10.1!

- 📄 [**Release notes**](https://github.com/mswjs/http-middleware/releases/tag/v0.10.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/http-middleware/v/0.10.1)

Make sure to always update to the latest version (`npm i @mswjs/http-middleware@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
