### PR TITLE
fix: ensure request body input is always a string

### LINKED ISSUE #17: Incoming request body has been parsed as [object Object]
Making POST request with JSON body, to mocked endpoint, produces body value as `[object Object]`.
The cause of this lays on using `express.json()` and then non-stringified JSON is changed to ArrayBuffer in `createMiddleware`.

Parsing text to JSON: 
https://github.com/mswjs/http-middleware/blob/ca849760dd3e32e990d33d66d393c101e5dc1f02/src/server.ts#L8

Encoding non-stringified JSON: https://github.com/mswjs/http-middleware/blob/ca849760dd3e32e990d33d66d393c101e5dc1f02/src/middleware.ts#L22

### LINKED ISSUE #18: Doesn't work when used with "express.json" middleware
Hey y'all big fan of MSW! 

I've been using MSW & http-middleware together to create a mock GraphQL API for a few months & I've recently run into an issue after updating to MSW v0.44.2 & http-middleware v0.5.0. I have a very similar setup to the [custom server](https://github.com/mswjs/http-middleware/blob/main/examples/custom-server.ts) example in this repo & after updating all GQL operations now seem to pass through & return a 404 "Mock not found". 

I've put together a [small example](https://github.com/nnnnat/msw-middleware-example) that reproduces the issue I'm seeing.

### PR DESCRIPTION
**Pull request by kettanaito**
- Fixes #18 
- Fixes #17

### CODE REVIEW

File: src/middleware.ts [hunk 1]
```diff
@@ -12,14 +12,20 @@ export function createMiddleware(
...
+
     const mockedRequest = new MockedRequest(
       // Treat all relative URLs as the ones coming from the server.
       new URL(req.url, serverOrigin),
       {
         method: req.method,
         headers: new Headers(req.headers as HeadersInit),
         credentials: 'omit',
-        body: encodeBuffer(req.body),
+        body: encodeBuffer(requestBody),
```
Comment (kettanaito) [inline src/middleware.ts:28]: With msw@0.44, the input for the `body` is always an ArrayBuffer that encodes a plain string. Previously, it was possible passing a plain object as well, that's why the issue surfaced only now.

**Comment by kettanaito** [comment]
## Released: v0.5.1 🎉

This has been released in v0.5.1!

- 📄 [**Release notes**](https://github.com/mswjs/http-middleware/releases/tag/v0.5.1)
- 📦 [npm package](https://www.npmjs.com/package/@mswjs/http-middleware/v/0.5.1)

Make sure to always update to the latest version (`npm i @mswjs/http-middleware@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.
